

#ifndef TIMER2_CONFIG_H_
#define TIMER2_CONFIG_H_

/*Options:
 * TIMER2_NORMAL
 * TIMER2_PWM_PHASE_CORRECT
 * TIMER2_CLR_ON_COMP
 * TIMER2_FAST_PWM
 */
#define TIMER2_WAVE_GEN_MODE    TIMER2_PWM_PHASE_CORRECT

/*Options:
 * TIMER2_OC2_DISCONNECTED
 * TIMER2_OC2_TOGGLE_OR_RESEREVED
 * TIMER2_OC2_CLR_ON_COMP_OR_NON_INVERTING_MODE
 * TIMER2_OC2_SET_ON_COMP_OR_INVERTING_MODE
 * */
/*Notes:
 * NON_INVERTING_MODE: Clear on compare, set at BOTTOM
 * /CLR on compare while up-counting, set on compare when down-counting
 * INVERTING_MODE:     SET on compare, clear at BOTTOM
 * /Set on compare when up-counting, clear on compare when down-counting.
 * */
#define TIMER2_OC2_MODE     TIMER2_OC2_CLR_ON_COMP_OR_NON_INVERTING_MODE

/*Options:
 * TIMER2_PRES_STOPPED
 * TIMER2_PRES_NO_PRESCALING
 * TIMER2_PRES_8
 * TIMER2_PRES_64
 * TIMER2_PRES_256
 * TIMER2_PRES_1024
 * TIMER2_EXTERNAL_CLK_T0_ON_FALLING_EDGE
 * TIMER2_EXTERNAL_CLK_T0_ON_RISING_EDGE
 * */
#define TIMER2_PRES_CLK  TIMER2_PRES_8

/*Options: Values from 0 --> 255
 * */
#define TIMER2_INIT_VALUE        0

/*Options: Values from 0-->255
 * */
#define TIMER2_INIT_COMP_VALUE   105

/*Options:
 * TIMER0_INT_ENABLED
 * TIMER0_INT_DISABLED
 * */
#define TIMER2_INIT_OVERFLOW_INT_STATE       TIMER2_INT_DISABLED

#define TIMER2_INTIT_COMP_MATCH_INT_STATE    TIMER2_INT_DISABLED

#endif
